name: "Manage Issue Labels"
author: "Prasad Tengse"
description: "Sync/Manage issue labels defined in .github/labels.toml"
branding:
  icon: "tag"
  color: "blue"
inputs:
  owner:
    description: "Repository owner's username"
    required: false
  repo:
    description: "Name of the repository (Without owner/org name)"
    required: false
  file:
    description: "Labels file"
    required: false
    default: ".github/labels.toml"
  token:
    description: "GitHub token"
    required: true
runs:
  using: "docker"
  image: "docker://tprasadtp/labels:0.3.0.20200214"
  entrypoint: /usr/local/bin/entrypoint.sh
